#!/usr/bin/env bash
# This bash script configures Nginx to run and listen on port 80 in an Ubuntu container

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
