#!/bin/bash

cat << EOF > /etc/nginx/sites-enabled/nginx_config
server {
    listen 8080 default_server;
    listen [::]:8080 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

service nginx start

